### ISSUE TITLE
Swarm and REX-Ray

### ISSUE THREAD

**Issue by clintkitson** [emccode/conferences#109]

**Comment by kacole2** [comment]
i'm more than happy to submit a talk on this but looking for some guidance on sticking points.
- today's pitfalls of volume drivers with swarm (https://github.com/docker/swarm/issues/1529 & https://github.com/docker/swarm/issues/1970)
- demo of swarm with rexray
- operationalizing persistent storage with clustered hosts
- uhh???

maybe i need to spin up a cluster real quick and test it out. haven't messed with it in a little while

**Comment by kacole2** [comment]
@clintonskitson take a look at this stab and see if this fits the Swarm/REX-Ray idea.

**Title:** Highly Available & Distributed Containers

**Abstract:**  Many of today's “Docker-in-production" applications are ephemeral and have a short life-span. However, enterprises want containers to run higher tier applications. Learn how to scale a typical 3-tier app using Swarm, serve a persistent database with Docker Volume drivers and tie them all together on a single private network with libNetwork. Then watch the automated recovery of stateful containers during a real-life HA (highly-available) scenario. Containers are ready to overtake the virtual machine as the next unit of infrastructure.

**Outline:** Enterprises are getting into the container world but are trying to figure out how to make their critical applications highly-available. The first goal to accomplish is making them realize that containers can be used instead of virtual machines. Move to a "container-first" strategy. 

You will see a standard 3-tier app, how many of today and yesterday’s applications are written, be deployed using a Compose file to a Swarm cluster. During provisioning, the persistent state needed for volumes are created on the fly as well as being added to a libNetwork private network. Then we will demonstrate the loss of a host where the database is running. Swarm will restart the container on a new host and REX-Ray's Pre-emption support will disconnect and attach the volume to the new host where the container is restarted. This use-case provides people a means to move beyond the virtual machine because they have a misconception of what containers are capable of.

**Key Takeaways:**
- Attendees will be able to see 4 different Docker technologies in use. Docker Swarm, Docker Compose, Docker Volumes/Drivers, and libNetwork
- The audience will gain a better understanding why the container can be seen as VM.next and interpret how they can move to a “container first” strategy.
- Learn how to make containers highly-available
- Availability to the code and instructions on how to setup their own cluster of hosts will be made available.
- Of course, a demo will be done to see it all in action
- All code and integrations used during the session are all Open Source.
