### ISSUE TITLE
ScaleIO and Heat

### ISSUE THREAD

**Issue by clintonskitson** [emccode/conferences#30]

**Comment by clintkitson** [comment]
@adrianmo You up for this one?

**Comment by adrianmo** [comment]
@clintonskitson Yup, no problem. But what is Heat supposed to do in this case? Deploy the SIO cluster and connect it to OS, like the SIO Fuel plugins?

**Comment by clintkitson** [comment]
My fault, I was referring to Fuel here.

**Comment by adrianmo** [comment]
Got it! I'll come up with something

**Comment by adrianmo** [comment]
@clintonskitson I have changed the topic a little bit. From my experience in OpenStack summits, presentations about specific products (ScaleIO, Fuel) are not very well considered since they don't want to run the risk of accepting a marketing presentation. In fact, they created a separate track for "Premium" (paid) presentations (which nobody attends to).

Take a look at the new title and abstract and let me know what you think.

Title: Comparing block storage backends for OpenStack

Abstract:
This presentation aims to provide a comprehensive and unbiased comparison of the different options available as block storage backends for OpenStack. We will only consider software solutions; therefore, solutions that rely on external hardware or services will not be included in the analysis. We will study some real-world block storage requirements and discuss about the performance and features offered by these solutions. We will also talk about the cost of constructing and operating them. By the end of the presentation, the audience will be aware of the options available for providing block storage on OpenStack and identify which one fits their particular needs best.

**Comment by clintkitson** [comment]
Ok I like it.

**Comment by amandakatona** [comment]
nice! can we remove "about" in this sentence? "and discuss about the performance and features offered by these solutions". Or is this implying it's an open discussion amongst the audience and us?

**Comment by adrianmo** [comment]
@amandakatona Thanks for the review. The presentation is not going to be an open discussion. So what if we change the sentence by this one: "...and review the performance and features offered by these solutions."

Please propose any other alternatives if you feel like it :)

**Comment by amandakatona** [comment]
That works!

**Comment by amandakatona** [comment]
@adrianmo Will you please submit to OpenStack Summit CFP? Once it's submitted will you please add the label as "submitted"? Still learning the process over here! It would also be helpful if you copy/pasted the submitted abstract in here in case we want to use it later. Thanks! 

https://www.openstack.org/summit-login/login?BackURL=%2Fsummit%2Faustin-2016%2Fcall-for-speakers%2F

**Comment by adrianmo** [comment]
@amandakatona Sure, I was planning to submit it tomorrow after I review it for the last time. I'll label it as well :)

**Comment by adrianmo** [comment]
Submitted
