### ISSUE TITLE
Docker Platform 101 

### ISSUE THREAD

**Issue by clintkitson** [emccode/conferences#55]

**Comment by kacole2** [comment]
Abstract: There is a new infrastructure taking over the datacenter. History is repeating itself because one company is looking to be the central provider for this new world. This session will cover how each Docker project provides developers and operations the ability to run, deploy, manage and monitor an entire Docker infrastructure. Learn all about Docker Engine, Machine, Compose, Swarm, Hub, Trusted Registry and more! Demos of each product will be provided as well as how each tie into EMC II technology.

**Comment by kacole2** [comment]
http://www.slideshare.net/EMCCODE/emc-world-2016-code09-introduction-to-the-docker-platform
