### ISSUE TITLE
Deploying Persistent Storage for Containers with Heat

### ISSUE THREAD

**Issue by mux23** [emccode/conferences#87]
Abstract: Containers have proven to be a popular subject in 2015, and now in 2016 it seems like every project manager thinks they're the magical solution to every application deployment problem. The reality is that there are some gaps, and storage persistence is a big one. With our open-source tool REX-Ray, we've solved the storage persistence problem, and pairing that technology with OpenStack Heat makes for an excellent toolchain for deploying cloud-native applications with persistent storage. In this presentation we'll talk about the reasons for storage persistence, showcase some example applications, and discuss ways to leverage these tools in your own application deployments.

**Comment by amandakatona** [comment]
Take em or leave em comments - can we qualify why "storage persistence is a big one"? storage persistence is a big one when you try to XYZ, or a big one because when you do X, Y happens, or ... 

Also, is there a way to personalize to this just a touch? something along the lines of "when we went to do X, we found we were missing Y so we created REX-Ray for the community (this may have not been what happened but adding in a personalized touch will show we are adding value to the community based on what we see is needed).

I actually want to hear the talk now...

**Comment by amandakatona** [comment]
@drumulonimbus how are we looking on this one?

**Comment by mux23** [comment]
hrm, not sure why this one didn't come up when I sorted the list by assignee last week.

new abstract: Containers have proven to be a popular subject in 2015, and now in 2016 it seems like every project manager thinks they're the magical solution to every application deployment problem. The reality is that there are some gaps, and storage persistence is a big one - if your application needs data that stays available past the short lifespan of a container, you might be out of luck. When we ran into this problem, we solved it by creating our open-source storage introspection tool REX-Ray, and pairing that technology with OpenStack Heat makes for an excellent toolchain for deploying cloud-native applications with persistent storage. In this presentation we'll talk about the reasons for storage persistence, showcase some example applications, and discuss ways to leverage these tools in your own application deployments.
